// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeletePasswordEntry(arg1:string):Promise<void>;

export function GeneratePassword(arg1:models.PasswordGenerationOptions):Promise<string>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetAppSettings():Promise<Record<string, any>>;

export function GetPasswordEntries():Promise<Array<models.PasswordEntry>>;

export function GetSystemFingerprint():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function SavePasswordEntry(arg1:models.PasswordEntry):Promise<models.PasswordEntry>;

export function UpdateAppSettings(arg1:Record<string, any>):Promise<void>;
