// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {controller} from '../models';
import {models} from '../models';

export function DeletePasswordEntry(arg1:string):Promise<void>;

export function ExportPasswordsEncrypted(arg1:string):Promise<controller.EncryptedBackupData>;

export function GeneratePassword(arg1:models.PasswordGenerationOptions):Promise<string>;

export function GetAppInfo():Promise<Record<string, any>>;

export function GetAppSettings():Promise<Record<string, any>>;

export function GetBackupOptions():Promise<Array<controller.BackupOption>>;

export function GetOwlLockFolderPath():Promise<string>;

export function GetPasswordEntries():Promise<Array<models.PasswordEntry>>;

export function GetSystemFingerprint():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function ImportPasswordsEncrypted(arg1:controller.EncryptedBackupData,arg2:string):Promise<void>;

export function SaveBackupToOwlLockFolder(arg1:controller.EncryptedBackupData,arg2:string):Promise<void>;

export function SavePasswordEntry(arg1:models.PasswordEntry):Promise<models.PasswordEntry>;

export function UpdateAppSettings(arg1:Record<string, any>):Promise<void>;

export function ValidateEncryptedBackup(arg1:string):Promise<controller.BackupMetadata>;
